version: '3.8'

services:
  auth:
    container_name: incidents-auth
    build: .
    ports:
      - "5555:5555"
    volumes:
      - ./logs:/usr/src/app/logs
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=5555
      - MONGO_CONNECTION_STRING=mongodb://mongo:27017/auth
      - RMQ_HOST=amqp://admin:admin@host.docker.internal:5672
    depends_on:
      - mongo
  mongo:
    container_name: incidents-mongo
    image: "mongo:latest"
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-data:/data

